### ISSUE TITLE
часть про дифуры

### ISSUE THREAD

**Issue by qiqvo** [qiqvo/Letter-for-good#16]
уточнить, что прикладные задачи интересно разбирать на практике (да и то не на каждой). Но их полное отсутствие -- это проблема

**Comment by ARKAD97** [comment]
На многих курсах мы обходились и без прикладных примеров, что не делало их менее увлекательными. Как уже было замечено в чатах, проблема не в отсутствии прикладных задач, а в качестве преподавания.
