### ISSUE TITLE
Как предмет назовешь так диплом и ценится

### ISSUE THREAD

**Issue by nika-skybytska** [qiqvo/Letter-for-good#18]
## Что
Обсудить разделение _(и удлинение)_ дискретной математики на предметы 
- "Теория множеств"
- "Математическая логика"
- "Комбинаторика"
- "Теория графов"
которые будут читаться на  протяжении двух курсов.
---
### Что надо для принятия решения:
* одобрение такого разбиения студентами (Ха Ву)
* одобрение такого разбиения преподами (Карнаух)
* обсудить обязательность каждого из курсов
---
### Что надо для воплощения принятого решения:
* ? добавить абзац/раздел в додаток об этом всем
* обновить дерево предметов
* ? накидать программу каждой части

**Comment by ARKAD97** [comment]
Решили же, что не разделяемпредметы, верно? Надо закрыть ишью
